#!/usr/bin/env bash
# Web servers are the piece of software generating and serving HTML pages, let’s install one!
apt-get update
apt-get install -y nginx
HOSTNAME=$(cat /etc/hostname)
sed -i "/listen \[::\]:80 default_server;/a \\\n\tadd_header X-Served-By \"$HOSTNAME\";" /etc/nginx/sites-enabled/default
service nginx restart
