#!/usr/bin/env bash
# configure HAproxy on your lb-01 server.
apt-get update
apt-get install -y haproxy
echo "frontend http
        bind *:80
        mode http
        default_backend web-backend

backend web-backend
        balance roundrobin
        server 3220-web-01 35.196.116.56:80 check
        server 3220-web-02 35.237.116.242:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
