#!/usr/bin/env bash
# Change the port listening of the nginx server by port 80.
sed -i 's/listen 8080/listen 80/g' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:8080/listen \[::\]:80/g' /etc/nginx/sites-enabled/default
service nginx restart
