#!/usr/bin/env bash
# This script is displaying "Best School" 8 times, in 4th display "bad luck" and in 8th display "good luck"
i=0
while [ $i -ne 10 ]; do
    if [ $i -eq 3 ]
    then
        echo "bad luck"
    elif [ $i -eq 7 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    (( i++ ))
done
