#!/usr/bin/env bash
# This script is displaying "Best School" 10 times, but in the 9th the shell say Hi
i=0
while [ $i -ne 10 ]; do
    if [ $i -eq 3 ]
    then
        echo "bad luck"
    elif [ $i -eq 7 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    (( i++ ))
done
