#!/usr/bin/env bash
# Display numbers starting at 1 to 20. 4, 9 and 17 have specials cases
i=1
while [ $i -ne 21 ]; do
    case $i in
    4)
        echo $i
        echo "bad luck from China"
        ;;
    9)
        echo $i
        echo "bad luck from Japan"
        ;;
    17)
        echo $i
        echo "bad luck from Italy"
        ;;
    *)
        echo $i
    esac
    (( i++ ))
done
