#!/usr/bin/env bash
# This script is displaying "Best School" 10 times, but in the 9th the shell say Hi
i=1
while [ $i -ne 21 ]; do
    case $i in
    4)
        echo "bad luck from China"
        ;;
    9)
        echo "bad luck from Japan"
        ;;
    17)
        echo "bad luck from Italy"
        ;;
    *)
        echo $i
    esac
    (( i++ ))
done
