#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes
hours=0
minutes=0
while [ $hours -ne 13 ]; do
    if [ $minutes -eq 0 ]
    then
        echo "Hour: $hours"
    else
        echo $minutes
    fi
    (( minutes++ ))
    if [ $minutes -eq 60 ]
    then
        minutes=0
        (( hours++ ))
    fi
done
